import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import UploadButton from "@/components/client/UploadButton";
import axios from "axios";
import {baseUrl} from "../../utils/constants";
import {useState} from "react";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [pickedImageUrls, setPickedImagesUrl] = useState([])
    const [isUploading, setIsUploading] = useState(false)
    const handleFileChange = async (e) => {
        const imageFiles = Array.from(e.target.files);
        for (let i = 0; i < e.target.files.length; i++) {
            const file = e.target.files[i]
            const url = URL.createObjectURL(file)
            console.log("adding image " + url)

            setPickedImagesUrl(pickedImageUrls => [...pickedImageUrls, url])
            console.log(pickedImageUrls)

        }
        let formData = new FormData();
        imageFiles.forEach((image) => formData.append("file", image));
        setIsUploading(true)
        var res = await axios.post("/api/image", formData);
        setIsUploading(false)

        console.log(res)
        if (res.data.image) {
            window.location.href = baseUrl + "/" + res.data.image
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={" w-screen h-screen  flex items-center justify-center " + inter.className}>
                <div className="w-full h-[80vh] overflow-hidden bg-white m-2 rounded-3xl flex flex-col md:flex-row md:h-[400px] md:w-[800px] border-2 border-light">
                    <div className="h-1/2 md:h-full md:w-1/2 bg-[#744FC6] box-border relative">
                        <h1 className="box-border tracking-wider m-6">
                            <span className="text-7xl md:text-9xl font-extrabold text-primary block">Size</span>
                            <span className="text-3xl md:text-4xl leading-10   line-h text-white">Matters! Resize Your.</span>
                            <span className="text-4xl md:text-5xl  text-primary block">Screenshots</span>
                        </h1>
                        <Image src={"/overlay.png"} fill={true} className="absolute"/>

                    </div>
                    <div className="h-1/2 md:h-full md:w-1/2 bg-[#3D405B] flex justify-center md:items-center ">
                       <div >
                           <Image src={"/upload.png"} height={150} width={150} alt="upload image" className="mx-auto my-3 "/>
                           <UploadButton loading={isUploading} onFilePick={handleFileChange}/>

                       </div>
                    </div>
                </div>

            </main>

        </>
    )
}
